name: multimodal
channels:
  - conda-forge
  - defaults
dependencies:
  - _tflow_select=2.3.0
  - abseil-cpp=20211102.0
  - absl-py=2.3.0
  - aiohappyeyeballs=2.6.1
  - aiohttp=3.12.6
  - aiosignal=1.3.2
  - aom=3.9.1
  - arrow-cpp=11.0.0
  - astunparse=1.6.3
  - async-timeout=5.0.1
  - attrs=25.3.0
  - aws-c-common=0.4.57
  - aws-c-event-stream=0.1.6
  - aws-checksums=0.1.9
  - aws-sdk-cpp=1.8.185
  - blas=1.0
  - blinker=1.9.0
  - boost-cpp=1.85.0
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - c-ares=1.34.5
  - ca-certificates=2025.4.26
  - cached-property=1.5.2
  - cached_property=1.5.2
  - cachetools=5.5.2
  - cairo=1.16.0
  - certifi=2025.4.26
  - cffi=1.17.1
  - charset-normalizer=3.4.2
  - click=8.2.1
  - colorama=0.4.6
  - contourpy=1.3.2
  - cryptography=39.0.0
  - cycler=0.12.1
  - datasets=2.14.4
  - dav1d=1.2.1
  - dill=0.3.7
  - dlib=19.24.0
  - eigen=3.4.0
  - expat=2.7.0
  - ffmpeg=4.2.3
  - filelock=3.18.0
  - flatbuffers=25.2.10
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.2
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.58.1
  - freetype=2.12.1
  - fribidi=1.0.10
  - frozenlist=1.6.0
  - fsspec=2025.5.1
  - gast=0.4.0
  - gdk-pixbuf=2.42.6
  - gettext=0.22.5
  - gettext-tools=0.22.5
  - gflags=2.2.2
  - giflib=5.2.2
  - glib=2.80.2
  - glib-tools=2.80.2
  - glog=0.5.0
  - google-auth=2.40.2
  - google-auth-oauthlib=0.4.6
  - google-pasta=0.2.0
  - graphite2=1.3.13
  - grpc-cpp=1.48.2
  - gst-plugins-base=1.18.5
  - gstreamer=1.18.5
  - h2=4.2.0
  - harfbuzz=2.4.0
  - hdf5=1.12.1
  - hpack=4.1.0
  - huggingface_hub=0.31.4
  - hyperframe=6.1.0
  - icu=58.2
  - idna=3.10
  - importlib-metadata=8.7.0
  - imutils=0.5.4
  - intel-openmp=2023.2.0
  - jinja2=3.1.6
  - joblib=1.5.1
  - jpeg=9e
  - kiwisolver=1.4.7
  - krb5=1.20.1
  - lame=3.100
  - lcms2=2.12
  - lerc=4.0.0
  - libabseil-static=20211102.0
  - libasprintf=0.22.5
  - libasprintf-devel=0.22.5
  - libblas=3.9.0
  - libboost=1.85.0
  - libboost-devel=1.85.0
  - libboost-headers=1.85.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcblas=3.9.0
  - libclang13=14.0.6
  - libcurl=8.1.2
  - libdeflate=1.24
  - libexpat=2.7.0
  - libffi=3.4.6
  - libgettextpo=0.22.5
  - libgettextpo-devel=0.22.5
  - libglib=2.80.2
  - libhwloc=2.9.1
  - libiconv=1.18
  - libintl=0.22.5
  - libintl-devel=0.22.5
  - libjpeg-turbo=2.1.4
  - liblapack=3.9.0
  - liblzma=5.8.1
  - liblzma-devel=5.8.1
  - libogg=1.3.5
  - libopus=1.5.2
  - libpng=1.6.43
  - libpq=12.15
  - libprotobuf=3.20.3
  - librsvg=2.50.3
  - libsqlite=3.50.0
  - libssh2=1.10.0
  - libthrift=0.15.0
  - libtiff=4.2.0
  - libusb=1.0.29
  - libuv=1.51.0
  - libvorbis=1.3.7
  - libwebp=1.5.0
  - libwebp-base=1.5.0
  - libxml2=2.10.4
  - libxslt=1.1.37
  - libzlib=1.2.13
  - lz4-c=1.9.4
  - markdown=3.8
  - markupsafe=3.0.2
  - matplotlib-base=3.10.1
  - mkl=2023.2.0
  - mkl-service=2.4.1
  - mpmath=1.3.0
  - multidict=6.4.4
  - multiprocess=0.70.15
  - munkres=1.1.4
  - networkx=3.4.2
  - numpy=1.26.4
  - oauthlib=3.2.2
  - opencv=4.6.0
  - openh264=2.6.0
  - openjpeg=2.4.0
  - openssl=1.1.1w
  - opt_einsum=3.4.0
  - orc=1.7.4
  - packaging=25.0
  - pandas=2.2.3
  - pango=1.42.4
  - pcre2=10.43
  - pillow=11.0.0
  - pip=25.1.1
  - pixman=0.46.0
  - portaudio=19.7.0
  - propcache=0.3.1
  - pthreads-win32=2.9.1
  - pyarrow=11.0.0
  - pyasn1=0.6.1
  - pyasn1-modules=0.4.2
  - pycparser=2.22
  - pyjwt=2.10.1
  - pyopenssl=23.2.0
  - pyparsing=3.2.3
  - pysocks=1.7.1
  - python=3.10.8
  - python-dateutil=2.9.0.post0
  - python-flatbuffers=25.2.10
  - python-sounddevice=0.5.2
  - python-tzdata=2025.2
  - python-xxhash=3.5.0
  - python_abi=3.10
  - pytorch=2.3.1
  - pytz=2025.2
  - pyu2f=0.1.5
  - pyyaml=6.0.2
  - qhull=2020.2
  - qt-main=5.15.2
  - qt-webengine=5.15.9
  - qtwebkit=5.212
  - re2=2022.04.01
  - regex=2024.11.6
  - requests=2.32.3
  - requests-oauthlib=2.0.0
  - rsa=4.9.1
  - safetensors=0.5.3
  - scikit-learn=1.6.1
  - scipy=1.15.2
  - sdl2=2.32.54
  - sdl3=3.2.14
  - sentence-transformers=4.1.0
  - setuptools=80.9.0
  - six=1.17.0
  - snappy=1.2.1
  - sqlite=3.50.0
  - svt-av1=3.0.2
  - sympy=1.14.0
  - tbb=2021.9.0
  - tensorboard-plugin-wit=1.8.1
  - tensorflow-estimator=2.10.0
  - termcolor=3.1.0
  - threadpoolctl=3.6.0
  - tk=8.6.13
  - tokenizers=0.21.1
  - tqdm=4.67.1
  - transformers=4.52.4
  - typing-extensions=4.13.2
  - typing_extensions=4.13.2
  - tzdata=2025b
  - ucrt=10.0.22621.0
  - unicodedata2=16.0.0
  - urllib3=2.4.0
  - utf8proc=2.6.1
  - vc=14.3
  - vc14_runtime=14.42.34438
  - vs2015_runtime=14.42.34438
  - webrtcvad=2.0.10
  - werkzeug=3.1.3
  - wheel=0.45.1
  - win_inet_pton=1.1.0
  - wrapt=1.17.2
  - x264=1!164.3095
  - x265=3.5
  - xxhash=0.8.3
  - xz=5.8.1
  - xz-tools=5.8.1
  - yaml=0.2.5
  - yarl=1.20.0
  - zipp=3.22.0
  - zlib=1.2.13
  - zstandard=0.23.0
  - zstd=1.5.6
  - pip:
      - annotated-types==0.7.0
      - anyio==4.9.0
      - distro==1.9.0
      - exceptiongroup==1.3.0
      - grpcio==1.72.1
      - h11==0.16.0
      - h5py==3.13.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - jax==0.6.1
      - jaxlib==0.6.1
      - jiter==0.10.0
      - keras==3.10.0
      - libclang==18.1.1
      - llvmlite==0.44.0
      - markdown-it-py==3.0.0
      - mdurl==0.1.2
      - mediapipe==0.10.21
      - ml-dtypes==0.5.1
      - more-itertools==10.7.0
      - namex==0.1.0
      - numba==0.61.2
      - openai==1.82.1
      - openai-whisper==20240930
      - opencv-contrib-python==4.11.0.86
      - optree==0.16.0
      - protobuf==4.25.8
      - pydantic==2.11.5
      - pydantic-core==2.33.2
      - pygments==2.19.1
      - pyqt5==5.15.11
      - pyqt5-qt5==5.15.2
      - pyqt5-sip==12.17.0
      - rich==14.0.0
      - sentencepiece==0.2.0
      - sniffio==1.3.1
      - tensorboard==2.18.0
      - tensorboard-data-server==0.7.2
      - tensorflow==2.18.1
      - tensorflow-io-gcs-filesystem==0.31.0
      - tf-keras==2.18.0
      - tiktoken==0.9.0
      - typing-inspection==0.4.1
