name: multimodal
channels:
  - conda-forge
  - defaults
dependencies:
  - absl-py=2.2.0
  - aiohappyeyeballs=2.6.1
  - aiohttp=3.11.18
  - aiosignal=1.3.2
  - arrow-cpp=19.0.0
  - astunparse=1.6.3
  - async-timeout=5.0.1
  - attrs=25.3.0
  - aws-c-auth=0.6.21
  - aws-c-cal=0.5.20
  - aws-c-common=0.8.5
  - aws-c-compression=0.2.16
  - aws-c-event-stream=0.2.15
  - aws-c-http=0.6.27
  - aws-c-io=0.13.11
  - aws-c-mqtt=0.7.13
  - aws-c-s3=0.2.1
  - aws-c-sdkutils=0.1.7
  - aws-checksums=0.1.13
  - aws-crt-cpp=0.18.16
  - aws-sdk-cpp=1.11.212
  - blas=1.0
  - boost-cpp=1.78.0
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - c-ares=1.34.5
  - ca-certificates=2025.4.26
  - cairo=1.16.0
  - certifi=2025.4.26
  - cffi=1.17.1
  - charset-normalizer=3.4.2
  - colorama=0.4.6
  - cycler=0.12.1
  - datasets=2.14.4
  - deprecated=1.2.18
  - dill=0.3.7
  - dlib=19.24.0
  - eigen=3.4.0
  - expat=2.7.0
  - ffmpeg=4.3.1
  - filelock=3.18.0
  - fontconfig=2.14.1
  - fonttools=4.58.0
  - freeglut=3.4.0
  - freetype=2.10.4
  - frozenlist=1.6.0
  - fsspec=2025.5.0
  - gast=0.6.0
  - gflags=2.2.2
  - giflib=5.2.2
  - glib=2.78.4
  - glib-tools=2.78.4
  - glog=0.5.0
  - google-pasta=0.2.0
  - graphite2=1.3.14
  - grpcio=1.71.0
  - gst-plugins-base=1.24.12
  - gstreamer=1.24.12
  - gstreamer-orc=0.4.41
  - h2=4.2.0
  - h5py=3.12.1
  - harfbuzz=10.2.0
  - hdf5=1.14.5
  - hpack=4.1.0
  - huggingface_hub=0.31.4
  - hyperframe=6.1.0
  - icc_rt=2022.1.0
  - icu=73.2
  - idna=3.10
  - importlib-metadata=8.6.1
  - imutils=0.5.4
  - intel-openmp=2023.2.0
  - jinja2=3.1.6
  - joblib=1.5.0
  - jpeg=9e
  - keras=3.10.0
  - krb5=1.20.1
  - lcms2=2.16
  - lerc=4.0.0
  - libabseil=20250127.0
  - libblas=3.9.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcblas=3.9.0
  - libcurl=8.12.1
  - libdeflate=1.22
  - libevent=2.1.12
  - libexpat=2.7.0
  - libffi=3.4.4
  - libglib=2.78.4
  - libgrpc=1.71.0
  - libhwloc=2.11.2
  - libiconv=1.18
  - liblapack=3.9.0
  - libpng=1.6.39
  - libpq=17.4
  - libprotobuf=5.29.3
  - libre2-11=2024.07.02
  - libssh2=1.11.1
  - libthrift=0.15.0
  - libtiff=4.7.0
  - libtorch=2.5.1
  - libuv=1.50.0
  - libwebp-base=1.5.0
  - libwinpthread=12.0.0.r4.gg4f2fc60ca
  - libxml2=2.13.8
  - lz4-c=1.9.4
  - markdown=3.8
  - markdown-it-py=3.0.0
  - markupsafe=3.0.2
  - matplotlib-base=3.5.3
  - mdurl=0.1.2
  - mkl=2023.2.0
  - mkl-service=2.4.1
  - ml_dtypes=0.5.1
  - mpmath=1.3.0
  - multidict=6.4.4
  - multiprocess=0.70.15
  - munkres=1.1.4
  - namex=0.0.9
  - networkx=3.4.2
  - numpy=1.26.4
  - opencv=4.10.0
  - openjpeg=2.5.2
  - openssl=3.1.0
  - opentelemetry-api=1.33.1
  - opt_einsum=3.4.0
  - optree=0.15.0
  - orc=2.1.1
  - packaging=25.0
  - pandas=2.2.3
  - pcre2=10.42
  - pillow=11.1.0
  - pip=25.1
  - pixman=0.46.0
  - portaudio=19.7.0
  - propcache=0.3.1
  - pyarrow=19.0.0
  - pycparser=2.22
  - pygments=2.19.1
  - pyparsing=3.2.3
  - pysocks=1.7.1
  - python=3.10.16
  - python-dateutil=2.9.0.post0
  - python-flatbuffers=25.2.10
  - python-sounddevice=0.5.2
  - python-tzdata=2025.2
  - python-xxhash=3.5.0
  - python_abi=3.10
  - pytorch=2.5.1
  - pytz=2025.2
  - pyyaml=6.0.2
  - qtbase=6.7.3
  - re2=2024.07.02
  - regex=2024.11.6
  - requests=2.32.3
  - rich=14.0.0
  - safetensors=0.5.3
  - scikit-learn=1.6.1
  - scipy=1.15.2
  - sentence-transformers=4.1.0
  - setuptools=78.1.1
  - six=1.17.0
  - sleef=3.8
  - snappy=1.2.1
  - sqlite=3.45.3
  - sympy=1.14.0
  - tbb=2021.13.0
  - tensorboard=2.18.0
  - tensorboard-data-server=0.7.0
  - tensorflow-base=2.18.1
  - termcolor=3.1.0
  - threadpoolctl=3.6.0
  - tk=8.6.14
  - tokenizers=0.21.1
  - tqdm=4.67.1
  - transformers=4.52.3
  - typing-extensions=4.13.2
  - typing_extensions=4.13.2
  - tzdata=2025b
  - ucrt=10.0.22621.0
  - unicodedata2=16.0.0
  - urllib3=2.4.0
  - utf8proc=2.6.1
  - vc=14.42
  - vc14_runtime=14.42.34438
  - vs2015_runtime=14.42.34438
  - webrtcvad=2.0.10
  - werkzeug=3.1.3
  - wheel=0.45.1
  - win_inet_pton=1.1.0
  - wrapt=1.17.2
  - xxhash=0.8.3
  - xz=5.6.4
  - yaml=0.2.5
  - yarl=1.20.0
  - zipp=3.21.0
  - zlib=1.2.13
  - zstandard=0.23.0
  - zstd=1.5.6
  - pip:
      - annotated-types==0.7.0
      - anyio==4.9.0
      - asttokens==3.0.0
      - backcall==0.2.0
      - beautifulsoup4==4.13.4
      - bleach==6.2.0
      - comtypes==1.4.11
      - contourpy==1.3.2
      - decorator==5.2.1
      - defusedxml==0.7.1
      - distro==1.9.0
      - docopt==0.6.2
      - exceptiongroup==1.3.0
      - executing==2.2.0
      - fastjsonschema==2.21.1
      - h11==0.16.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - ipython==8.12.3
      - jax==0.6.1
      - jaxlib==0.6.1
      - jedi==0.19.2
      - jiter==0.10.0
      - jsonschema==4.24.0
      - jsonschema-specifications==2025.4.1
      - jupyter-client==8.6.3
      - jupyter-core==5.8.1
      - jupyterlab-pygments==0.3.0
      - kiwisolver==1.4.8
      - libclang==18.1.1
      - llvmlite==0.44.0
      - matplotlib==3.7.1
      - matplotlib-inline==0.1.7
      - mediapipe==0.10.21
      - mistune==3.1.3
      - more-itertools==10.7.0
      - nbclient==0.10.2
      - nbconvert==7.16.6
      - nbformat==5.10.4
      - numba==0.61.2
      - openai==1.82.1
      - openai-whisper==20240930
      - opencv-contrib-python==4.11.0.86
      - pandocfilters==1.5.1
      - parso==0.8.4
      - pickleshare==0.7.5
      - platformdirs==4.3.8
      - prompt-toolkit==3.0.51
      - protobuf==4.25.7
      - pure-eval==0.2.3
      - pydantic==2.11.5
      - pydantic-core==2.33.2
      - pypiwin32==223
      - pyqt5==5.15.11
      - pyqt5-qt5==5.15.2
      - pyqt5-sip==12.17.0
      - pyttsx3==2.98
      - pywin32==310
      - pyzmq==26.4.0
      - referencing==0.36.2
      - rpds-py==0.25.1
      - sentencepiece==0.2.0
      - sniffio==1.3.1
      - soupsieve==2.7
      - stack-data==0.6.3
      - tensorflow==2.18.1
      - tensorflow-io-gcs-filesystem==0.31.0
      - tf-keras==2.18.0
      - tiktoken==0.9.0
      - tinycss2==1.4.0
      - tornado==6.5.1
      - traitlets==5.14.3
      - typing-inspection==0.4.1
      - wcwidth==0.2.13
      - webencodings==0.5.1
      - yarg==0.1.9
